### ISSUE TITLE
Using hotspot On Windows Host After Profiling On Linux System

### ISSUE THREAD

**Issue by PatilChetan** [KDAB/hotspot#136]
Hi All,

The remote server I have is running CentOS where I profile all the workload using Linux Perf. However, the host machine I have is Windows 10. 

I want to make use of CPU FlameGraphs with this hotspot tool for better visualization, but don't think hotspot is supported on Windows. X server based connection doesn't always work as expected.

Please suggest what should I do in such case?

Thanks.

**Comment by milianw** [comment]
We'd first need to figure out how to make elfutils work on Windows. Afaik Ulf Hermann from TQC has been working on that for QtCreator's perf integration. Once we have that, building hotspot for windows shouldn't be too hard. We'll have to fix some platform specific things here and there, but otherwise it should be straight forward, compared to getting elfutils to work on Windows.

But: I personally don't have any incentive to work on this task right now. So someone else (you?) needs to step up and to the work required to make hotspot work on Windows.

**Comment by PatilChetan** [comment]
Hi Milian, 

I would like to do this, but I never worked on Qt and related programming environments. It will take a lot of time for me to get up to the level required to get this done.

Still willing to help, need inputs.

Thanks.

**Comment by milianw** [comment]
The first task isn't related to Qt at all. It's about figuring out how to compile elfutils on Windows. You'll probably need gnulib. Anything else needs to be figured out, I can't help more.

Once we have elfutils on Windows, we can use it for perfparser and then both for Hotspot.

**Comment by PatilChetan** [comment]
@milianw:

Do you think HotSpot can work on [Windows Subsystem For Linux](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux)?

**Comment by milianw** [comment]
@PatilChetan yes that can potentially work, if you get the gui/X to work. Afaik it's somehow possible, but requires some work.

**Comment by PatilChetan** [comment]
@milianw:

I can confirm that Hotspot works with WSL Ubuntu on Windows 10. Steps are same as building it on any Linux server as long as one has enabled WSL on Windows 10:

- Step 1: Build Hotspot as per the README on this repo on WSL Ubuntu shell on Windows 10
- Step 2: Configure X server on WSL Ubuntu shell on Windows 10
- Step 3: Install Xming on Windows 10
- Step 4: Enjoy

Screenshot:

![hotspot](https://user-images.githubusercontent.com/1078444/44179730-722ae400-a0ad-11e8-873a-d0777b92d4c8.png)
