### ISSUE TITLE
Support JIT'd code (jitdump support)

### ISSUE THREAD

**Issue by vchuravy** [KDAB/hotspot#160]
Perf has support to profilining jitted code (see https://lwn.net/Articles/638566/).
The flow roughly looks like follows:

1. The JIT compiler dumps debuginfo and object code in a file (format spec https://lore.kernel.org/patchwork/patch/725180/)
2. `perf inject -i perf.data -jit -o perf.data.jitted` injects the data back into the perf.data file and does post-processing
3. Post-processing involved to create ELF files that contain the symbols and object-code for each compilation unit

Currently hotspot unable to resolve JITT'ed symbols (after injecting and post-processing), due to the created `so` files not having `program headers`

```
failed to report elf for pid = 32101 : ElfInfo{localFile="/home/vchuravy/.debug/home/vchuravy/.debug/jit/llvm-IR-jit-20181127-2d5611/jitted-32101-31.so/051ad205ee66ee79f0e036a01c37a7459d1cd4eb/elf", isFile=true, originalFileName="jitted-32101-31.so", originalPath="/home/vchuravy/.debug/jit/llvm-IR-jit-20181127-2d5611/jitted-32101-31.so", addr=7f34a47b0b90, len=c4, pgoff=40, baseAddr=n/a} : No ELF program headers
```

```
~/.debug/jit/llvm-IR-jit-20181127-c11502$ readelf --program-headers jitted-26218-11.so 

There are no program headers in this file.
```

I should note that it is not the JIT-compiler who creates these object-files, but rather `perf inject`, and `perf` seems to ignore the program headers.

**Comment by milianw** [comment]
Yes, very true. see also the following patch series for more information on how this is handled in perf proper:

https://lwn.net/Articles/633846/

hotspot currently only supports perf.map files

**Comment by jasonk000** [comment]
KDAB hotspot relies on a more complete ELF file than perf currently outputs in order to be able to read and load in the jitdump generated ELF files. Specifically, it relies on the inclusion of a program header within the file. In addition, there is a change required for practical workloads with jitdump so that mappings will persist past JIT code area remappings.

More info here including potential patch:
https://gist.github.com/jasonk000/410a370d6ddc2bd4d8360a1a98f0bc8e

Would appreciate feedback on the approach and if so we can raise a PR here and would need to get some PRs upstreamed to perf.

This is only a starting point, and would need more work to support JIT languages in practice since Hotspot treats the same function recompiled by Java C2 as separate binaries. In addition, line number support shows as ??. Nonetheless, this is a starting point which we can expand over time.

**Comment by vchuravy** [comment]
@jasonk000 did you ever end up upstreaming your changes?

**Comment by jasonk000** [comment]
@vchuravy I would need to refresh my memory on this. It seems like the underlying issue has been fixed at some point. Could you confirm?

Today, when I use [perf-jitdump-agent](https://github.com/sfriberg/perf-jitdump-agent), (which has a `jitdump-record` script which performs `perf inject`). KDAB hotspot is then able to (mostly) correctly render the jitdump output.

**Comment by milianw** [comment]
apparently this works as indicated by jason above, so I'm going to close this. if there's more work required here, please indicate so (and ideally provide patches as I'm not working on any languages with jitdump support myself)
