### ISSUE TITLE
feature: open editor on function

### ISSUE THREAD

**Issue by grandinj** [KDAB/hotspot#205]
I'd like to be able to right click on a function and have something that says "open editor".

That should do a shell and execute a command which passes the file name of the function to an editor command.

For bonus points, make the editor configurable with some kind of format string that allows me to insert the line number of the function.

For example, I want to be able to run
  codelite <filename> -l <linenumber>
so that it switches to my IDE, opens the file, and jumps to the right function.

thanks

**Comment by milianw** [comment]
You can already do that from within the location table in the caller callee view (bottom right table). The editor is already configurable via the settings menu of hotspot.

otherwise, I agree that it would be nice to get a general `open function` action added to the other views, which will just open the first location we know for a given function

**Comment by grandinj** [comment]
cool, thanks!
