### ISSUE TITLE
libc debug information is not taken from Ubuntu libc6-dbg

### ISSUE THREAD

**Issue by dmikushin** [KDAB/hotspot#265]
**Describe the bug**
The symbols from system libraries such as libc are not properly imported into the profiling results.

**To Reproduce**
1. Do `sudo apt install libc6-dbg` and try to profile a code, which calls a libc function
2. Despite the debug information is available, the libc symbols will be shown "??" in hotspot (see screenshot)

**Expected behavior**
The actual libc symbol name is expected instead of ??

**Version Info (please complete the following information):**
 - Linux Kernel version: 5.4.0
 - perf version: 5.4.60
 - hotspot version: AppImage

**Additional context**

![Screenshot from 2020-10-21 12-01-02](https://user-images.githubusercontent.com/5672874/96705418-8d809080-1395-11eb-96f4-97c24cb70fa6.png)

**Comment by raphinesse** [comment]
It works for me when I run hotspot with `--debugPaths /usr/lib/debug`. Worked it out by trial and error.

**Comment by milianw** [comment]
What version of Ubuntu are you using? Can you create a small MWE to trigger this behavior? Then I may find some time to fire up ubuntu in docker to investigate this.

What's odd is that you are saying that passing `--debugPaths /usr/lib/debug` helps. The default path is:

```
//usr/lib/debug:/home/milian/.debug:.debug
```

I believe the double-slash shouldn't matter, and the separator is `:`. So that path you are specifying is already in there? Can you please try this on your machine:

```
strace -e file -f hotspot |& grep debug
```

And look at the paths it's trying to access? I definitely see accesses to `/usr/lib/debug` on my non-ubuntu machine...

**Comment by raphinesse** [comment]
> What version of Ubuntu are you using?

20.04. But it has been like that for a few versions

> Can you create a small MWE to trigger this behavior? Then I may find some time to fire up ubuntu in docker to investigate this.

I'll see what I can do, but I don't know when I'll find the time. I usually use hotspot on recordings of single process runs that contain cycles, cache and branch misses using DWARF info. Something like calling std::sort on a large array.

> What's odd is that you are saying that passing `--debugPaths /usr/lib/debug` helps. The default path is:
> 
> ```
> //usr/lib/debug:/home/milian/.debug:.debug
> ```
> 
> I believe the double-slash shouldn't matter, and the separator is `:`. So that path you are specifying is already in there?

Yes, that's what irritated me too when I first looked into this. The double slash is not a problem, I verified that. It's been since time since I investigated this issue, but I'll try to summarize from memory what I learned then:

IIRC, the essential part of the workaround was _removing all other paths_. That too might seem strange at first because the remaining path was first in the list anyway so it should take precedence over the others, right? But it makes sense when you look at the algorithm that is employed to find the debug symbols (I think it was part of  elfutils but you probably know where to look for it). IIRC, it was not a simple first-match-wins, but instead took multiple passes over the provided paths. I think it first looks for hashed (I think 🤔) debug symbols (I think they were symbols specific to a certain program run or something like that. My memory is very hazy on that detail), then for regular ones. And I think what happened was that it found a hashed match in `~/.debug` (which might have been created by `perf record`) and then used that before even looking for the regular symbols in the system directory. However, the matched symbols did not work as expected. So I came up with the workaround of removing all the other search paths which seems to be working fine for me. 

I hope this helps somewhat. I stopped looking into it then because I was short on time and way beyond my area of expertise.

**Comment by milianw** [comment]
We have some custom logic in `PerfSymbolTable::findDebugInfo`. But one way or another - finding a build-id matching entry in `~/.debug/` should be all that's needed.

I would suggest anyone who looks into this (@lievenhey ?) to try to reproduce this. Then look at the file listing withing `~/.debug` and paste it here and also get a file listing for the related libs in `/usr/lib` and `/usr/lib/debug` along with the output of `readelf --string-dump=.gnu_debuglink`.

**Comment by lievenhey** [comment]
.debug:
```
./[vdso]
./[vdso]/c3a5b2e4278d5905c200ad6427e2ad8d76ec2a28
./[vdso]/c3a5b2e4278d5905c200ad6427e2ad8d76ec2a28/probes
./[vdso]/c3a5b2e4278d5905c200ad6427e2ad8d76ec2a28/vdso
./usr
./usr/bin
./usr/bin/python3.8
./usr/bin/python3.8/02526282ea6c4d6eec743ad74a1eeefd035346a3
./usr/bin/python3.8/02526282ea6c4d6eec743ad74a1eeefd035346a3/elf
./usr/bin/python3.8/02526282ea6c4d6eec743ad74a1eeefd035346a3/probes
./usr/lib
./usr/lib/x86_64-linux-gnu
./usr/lib/x86_64-linux-gnu/libpthread-2.31.so
./usr/lib/x86_64-linux-gnu/libpthread-2.31.so/e54761f7b554d0fcc1562959665d93dffbebdaf0
./usr/lib/x86_64-linux-gnu/libpthread-2.31.so/e54761f7b554d0fcc1562959665d93dffbebdaf0/elf
./usr/lib/x86_64-linux-gnu/libpthread-2.31.so/e54761f7b554d0fcc1562959665d93dffbebdaf0/debug
./usr/lib/x86_64-linux-gnu/libpthread-2.31.so/e54761f7b554d0fcc1562959665d93dffbebdaf0/probes
./usr/lib/x86_64-linux-gnu/libc-2.31.so
./usr/lib/x86_64-linux-gnu/libc-2.31.so/099b9225bcb0d019d9d60884be583eb31bb5f44e
./usr/lib/x86_64-linux-gnu/libc-2.31.so/099b9225bcb0d019d9d60884be583eb31bb5f44e/elf
./usr/lib/x86_64-linux-gnu/libc-2.31.so/099b9225bcb0d019d9d60884be583eb31bb5f44e/probes
./filetree
./.build-id
./.build-id/02
./.build-id/02/526282ea6c4d6eec743ad74a1eeefd035346a3
./.build-id/9a
./.build-id/9a/e838e603db988d68009a8c3deb0cb1184c6824
./.build-id/e5
./.build-id/e5/4761f7b554d0fcc1562959665d93dffbebdaf0
./.build-id/09
./.build-id/09/9b9225bcb0d019d9d60884be583eb31bb5f44e
./.build-id/c3
./.build-id/c3/a5b2e4278d5905c200ad6427e2ad8d76ec2a28
./[kernel.kallsyms]
./[kernel.kallsyms]/9ae838e603db988d68009a8c3deb0cb1184c6824
./[kernel.kallsyms]/9ae838e603db988d68009a8c3deb0cb1184c6824/kallsyms
```

readelf for libc:
```
String dump of section '.gnu_debuglink':
  [     0]  libc-2.31.so
```
readelf for libpthread
```
String dump of section '.gnu_debuglink':
  [     0]  4761f7b554d0fcc1562959665d93dffbebdaf0.debug
  ```

**Comment by Hoernchen** [comment]
libc missing 12 out of 13 debug symbols, but it works after rm-rfing ~/.debug:

Ubuntu 18.04.5 LTS with mainline 5.13.0-rc6+ kernel, matching perf version 5.13.rc6.g913ec3c22ef4
hotspot f1ef65a845bb50f70985a8c06798612fce436b34 (current master)

`$readelf -wk /lib/x86_64-linux-gnu/libc-2.27.so`
Contents of the .gnu_debuglink section:

  Separate debug info file: libc-2.27.so
  CRC value: 0x8713c55a


`$crc32 /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so `
8713c55a


`$readelf -n -p .gnu_debuglink /lib/x86_64-linux-gnu/libc-2.27.so `

String dump of section '.gnu_debuglink':
  [     0]  libc-2.27.so
  [    10]  Z�^S


Displaying notes found in: .note.gnu.build-id
  Owner                 Data size	Description
  GNU                  0x00000014	NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: ce450eb01a5e5acc7ce7b8c2633b02cc1093339e

`$find ~/.debug -iname "*ce450eb01a5e5acc7ce7b8c2633b02cc1093339e*"`
~/.debug/lib/x86_64-linux-gnu/libc-2.27.so/ce450eb01a5e5acc7ce7b8c2633b02cc1093339e

**Comment by lievenhey** [comment]
I found it. By running hotspot with `--debugPaths /usr/lib/debug` libunwind starts looking around in /usr/lib/debug and finds the correct file (/usr/lib/debug/lib/x86_64-linux-gnu/libc-2.31.so (my case)).
Without the argument libunwind fails to find the file and PerfSymbolTable::findDebugInfo tries to find it. But it only finds /usr/lib/ x86_64-linux-gnu/libc-2.31.so which does not contain symbols.

**Comment by milianw** [comment]
We don't use libunwind in hotspot - do you mean elfutils / libdwfl?
