### ISSUE TITLE
document search for source files

### ISSUE THREAD

**Issue by lievenhey** [KDAB/hotspot#482]
Currently you can use `--debugPaths` and `--extraLibPaths` to add a path to the disassembler for source code search.

I don't know if we should use these paths or add new ones.

**Comment by GitMensch** [comment]
I'd vote for `--sourcePaths` because you commonly have the symbol files - which the old options can adjust post-recording - in the place that they had during recording, but the source is often kept separate from binaries/debug info and may not was in the place it had during recording (_especially_ when recording with an external library where you get the matching source afterwards and have that local).

**Comment by GitMensch** [comment]
Solved with #497 and should be closed as fixed.
