### ISSUE TITLE
Display which debug symbols are missing in summary

### ISSUE THREAD

**Issue by tmcguire** [KDAB/hotspot#54]
Without debug symbols, it is hard to interpret the data because the function name can not be displayed. Even worse is that many backtraces will be broken because unwinding fails, resulting in wrong data being displayed.

Hotspot should show which debug symbols are missing in the summary view, to alert the user about the problem.

Idealy it would even show how many samples make use of the library without debug symbols, so one can judge how important the debug symbols for that library are.

**Comment by milianw** [comment]
this is now implemented to some degree, but we can improve it further with your other suggestions

**Comment by raphinesse** [comment]
> Idealy it would even show how many samples make use of the library without debug symbols, so one can judge how important the debug symbols for that library are.

I'm not sure if the number of samples that use a symbol are that helpful. I often have one unresolved address, even for modules that have debug symbols present, that is the bottom of **all** stack traces. The number of samples for that would be huge, but it does not really matter that it is unresolved.

I would rather display the number of missing & total symbols per module. That way I can quickly see if I'm missing most or just a few of the symbols for a module.

**Comment by GitMensch** [comment]
The new version is better than the old open, but I have a lot of "is missing 1 of 3/10/15 debug symbols" - is there a way to debug that and find out which debug symbols are missing?

**Comment by raphinesse** [comment]
I can confirm that I usually have a few symbols per binary missing too. It's annoying but I usually only see such missing symbols in the bottom-most stack frame or such. It sure would be great to further improve that.

**Comment by milianw** [comment]
Yeah I guess the problem is related to the limited stack copy size. Just out of curiosity - when you increase the stack size (see `man perf record`), does the error eventually disappear? Generally though, please create a new issue instead of adding stuff to a task that's been closed for half year already

**Comment by GitMensch** [comment]
> Just out of curiosity - when you increase the stack size (see `man perf record`), does the error eventually disappear?

I guess that was about `-m` ? I've got root access just to try this, the result is unchanged (nearly it now had 4 modules more in the perf file which were previously missing). bash, libstdc++ and many others have 1 symbol missing (special case currently: `perf record` on RHEL7 and because of "missing libfuse" running hotspot on CentOS7 with the profiled application's binaries copied over and hinted to by `--extraLibPaths`).

In this specific case I've posted here because this issue is exactly about "which debug symbols are missing" (one _could_ even argue that it may be useful to reopen this issue because of this "commonly" asked issue not being solved [it possibly is not even possible to solve - I don't know]).

**Comment by milianw** [comment]
No it's not about `-m`, it's about the stack size used for dwarf unwinding:

```
                   - 'call-graph': Disable/enable callgraph. Acceptable str are "fp" for
                                  FP mode, "dwarf" for DWARF mode, "lbr" for LBR mode and
                                  "no" for disable callgraph.
                   - 'stack-size': user stack size for dwarf mode
...
               When "dwarf" recording is used, perf also records (user) stack dump
               when sampled.  Default size of the stack dump is 8192 (bytes).
               User can change the size by passing the size after comma like
               "--call-graph dwarf,4096".
```

Regarding the question "which debug symbols are missing" - if we'd know which symbol is missing, we wouldn't be missing it ;-) We only know that a given address couldn't be resolved. I don't think it would be helpful to anyone if we'd make the error message more explicit and say something like:

```
libFoo was missing 1 debug symbols:
0xDEADBEEF, size 128
```

Or would it?

**Comment by GitMensch** [comment]
Thank you for the information. increasing the stack-size to 32k increased the perf.data size by the amount of 3, lead to 990 instead of 20 chunks lost, added one more module that was previously not in the list of called modules, and: it lead to 30% less missing debug symbols. So the answer to your initial question was: yes, increasing the stack size helped.

**Comment by GitMensch** [comment]
Thank you, I've already read about that and looking forward to use it (but not possible on RHEL7 or CentOS7 without manual update which won't happen). I've learned quite a bunch of stuff and all questions are answered here. Going to the next ones...
