### ISSUE TITLE
copyright year needs an adjustment

### ISSUE THREAD

**Issue by GitMensch** [KDAB/hotspot#580]
the license file has

> Copyright (C) 2016-2020 Klaralvdalens Datakonsult AB

Side note: Would you consider "updating" the license to GPLv3+?

**Comment by milianw** [comment]
why do you want to update the license?

**Comment by GitMensch** [comment]
The copyright year change in the was last done in 6f4dc6a0904c239c8844e2325a1668b2d4aabcb9.

I think that one either considers to specify the copyright for the license, in which case the current entry makes no sense, or to specify not also the license but also the copyright for the software in a single place, in which case the years should be updated.

@winterz just adjusted the license in https://github.com/KDAB/KDDockWidgets/blob/2.0/LICENSE.GPL.txt to explicit allow _both_ license versions to be used (sadly it does not include "or any later version", but that's up to the copyright owner, of course).

For a general note about possible reasons to upgrade see https://www.gnu.org/licenses/rms-why-gplv3.html (for many the reason "I can link to GPLv3" will be the most relevant reason).

**Comment by milianw** [comment]
I believe the year is pretty meaningless - at least outside the US. But my colleague Allen (@winterz) regularly updates the year, which is fine by me.

Generally we try to use the same licenses for all our FOSS products here at kdab, are you saying KDDW is incompatible with hotspot? I doubt that, and if need be we can change the two licenses.

But I definitely do not intend to change the license "just because".
