### ISSUE TITLE
annotate source

### ISSUE THREAD

**Issue by milianw** [KDAB/hotspot#9]
add an "annotate source" view, similar to what other profilers have:

- source code with cost aggregated by line, show both inclusive/exclusive cost if possible
- assembly code with cost per instruction, again if possible also show inclusive cost for callq & friends

**Comment by tmcguire** [comment]
Yep, this would be quite useful for all event types like branch misses, for which you want to compare the different "if" statements inside a function.

**Comment by milianw** [comment]
The caller/callee view already will show the information you are looking for. This task is more about a "proper" source code view that allows one to see the code context directly, without having to open the code manually.

**Comment by bschindler** [comment]
I'd like to vote for this and point out one point which I think is really crucial: Since hotspot collects inline calls, the annotated source view should definately not do it the way kcachegrind or perf annotate do it - take assembly instructions and annotate one by one which gets you an incredibly hard to read mashed together source annotation in particular due to inlining. 

What I'd expect from this is to get the annotation centered around a function of source code. lets assume I have code like: 
```
void fun()
{
    auto value = computeValue();
    gVec.push_back(value);
    std::cout << "Done inserting" << std::endl;
}
```
I'd expect to just see that code and a highlighting on how much time was spent on each line. If push_back took 80%, I want to zoom into push_back and see its full implementation and what takes time in there, even if the code was inlined. This is what vtune does and it is soo much more useful than what objdump/kcachegrind/perf annotate do. 
An assembly oriented view is very useful as well, but for first stop profiling, source centric display is much more effective. 
May be you had the same intent here, but I just wanted to make sure...

**Comment by milianw** [comment]
@bschindler I completely agree, though vtune afaik shows only self-cost, not inlined cost in the annotate view, no? I actually plan to show both, self and inclusive cost.

I also think that an instruction-level annotation view is useful though. In a perfect world, it would also make it easy to associate instructions to source code, similar to https://godbolt.org/

**Comment by bschindler** [comment]
Instruction level annotation is hugely useful, I fully agree and godbolt got it just wonderfully. What I think sets godbolt apart from say objdump is that godbolt does it side by side using color annotation which I think works a lot better

**Comment by bschindler** [comment]
Instruction level annotation is hugely useful, I fully agree and godbolt got it just wonderfully. I never learnt to read assembly as well as with godbolt. What I think sets godbolt apart from say objdump is that godbolt does it side by side using color annotation which I think works a lot better. 

About vtune, I actually more had in mind that it showed inclusive cost and not self, but may be there is an option to see both? I agree that both is very valuable, in particular when dealing with recursion

**Comment by obfuscated** [comment]
Any progress with this feature?

**Comment by milianw** [comment]
No, I rarely see the need for this view myself and thus don't have a large incentive to work on this myself. Help wanted! Otherwise, please stay tuned until we get to this eventually.

**Comment by GitMensch** [comment]
Mainly commenting to subscribe ;-)

Just for reference: that's the way `perf report` annotates the code - including disassembly which I personally find really useful:

```
Samples: 241K of event 'cpu-clock:uhH', 32768 Hz, Event count (approx.): 7368451718
cob_decimal_set_packed  /foss/gnucobol-3.1.2/lib/libcob.so.4.1.0 [Percent: local period]
Percent│             if (sign < 0) {
  0.45 │1b1:   cmpl   $0x0,-0x24(%rbp)
  2.54 │       jns    1ca
       │                     mpz_neg (d->value, d->value);
       │       mov    -0x38(%rbp),%rdx
       │       mov    -0x38(%rbp),%rax
       │       mov    %rdx,%rsi
       │       mov    %rax,%rdi
       │       callq  __gmpz_neg@plt
       │             }
       │             d->scale = COB_FIELD_SCALE(f);
  1.27 │1ca:   mov    -0x40(%rbp),%rax
  0.54 │       mov    0x10(%rax),%rax
  1.36 │       movzwl 0x4(%rax),%eax
  3.54 │       movswl %ax,%edx
  1.18 │       mov    -0x38(%rbp),%rax
       │       mov    %edx,0x10(%rax)
       │     }
  1.27 │       leaveq
  0.27 │       retq
```
